name: gif_dart
description: Dart GIF encoder. A library for Dart developers. Full-featured JavaScript GIF encoder that runs in your browser. Uses typed arrays and web workers to render each frame in the background, it's really fast! This library wrap gif.js(https://github.com/jnordberg/gif.js).
# version: 1.0.0
# homepage: https://www.example.com
# author: dennougorilla <dennougorilla@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  js: ^0.6.0
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
